[Chainstore]
    EnableSplitstore = true
    [Chainstore.Splitstore]
        ColdStoreType = "discard"
        HotStoreFullGCFrequency = 0
        HotStoreMaxSpaceTarget = 0

[Storage]
    [Storage.File]
        [Storage.File.CSV]
            Format = "CSV"
            Path = "/tmp/data"
            OmitHeader = false
            FilePattern = "{table}.csv"

[Fevm]
    EnableEthRPC = true
 
