[API]
    Timeout = "5m"

[Storage]
    [Storage.File]
        [Storage.File.CSV]
            Format = "CSV"
            Path = "/tmp/data"
            OmitHeader = true
            FilePattern = "{jobname}-{table}.csv"
