[Storage]
    [Storage.File]
        [Storage.File.CSV]
            Format = "CSV"
            Path = "/tmp/data"
            OmitHeader = false
            FilePattern = "{table}.csv"
[API]
    Timeout = "180s"
