name: docker

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: build image
        run: docker build .

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - id: auth
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{raw}}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            europe-west1-docker.pkg.dev/protocol-labs-data/pl-data/filet:${{ steps.meta.outputs.version }}
            europe-west1-docker.pkg.dev/protocol-labs-data/pl-data/filet:latest
